/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ksaito.study2023.app;

public class App {
    public static void main(String[] args) {
        if (args.length < 1) {
            printHelp();
            return;
        }

        switch (args[0]) {
            case "--help":
                printHelp();
            case "nozaki":
                System.out.println("未実装です。");
            case "nakamaki":
                System.out.println("未実装です。");
            case "murata":
                System.out.println("未実装です。");
            case "gohara":
                System.out.println("未実装です。");
            default:
                printHelp();
        }
    }

    private static void printHelp() {
        System.out.println("実行アプリを指定してください。指定可能アプリは以下の通りです。");
        System.out.println("nozaki, nakamaki, murata, gohara");
    }
}
