/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ksaito.study2023.app;

import ksaito.study2023.common.AppException;
import ksaito.study2023.nakamaki.Omikuji;

public class App {
    public static void main(String[] args) {
        if (args.length < 1) {
            printHelp();
            return;
        }

        try {
            switch (args[0]) {
                case "--help":
                    printHelp();
                    break;
                case "nozaki":
                    System.out.println("未実装です。");
                    break;
                case "nakamaki":
                    new Omikuji().run(args);
                    break;
                case "murata":
                    System.out.println("未実装です。");
                    break;
                case "gohara":
                    System.out.println("未実装です。");
                    break;
                default:
                    printHelp();
            }
        } catch (AppException e) {
            System.out.println(e.getMessage());
        }
    }

    private static void printHelp() {
        System.out.println("実行アプリを指定してください。指定可能アプリは以下の通りです。");
        System.out.println("nozaki, nakamaki, murata, gohara");
    }
}
