/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ksaito.study2023.app;

import ksaito.study2023.common.exception.AppException;
import ksaito.study2023.gohara.Suggest;
import ksaito.study2023.murata.SubscriptionManagement;
import ksaito.study2023.nakamaki.Omikuji;
import ksaito.study2023.nozaki.IncomeAndExpenditureManagement;

public class App {
    public static void main(String[] args) {
        if (args.length < 1) {
            printHelp();
            return;
        }

        try {
          switch (args[0]) {
            case "--help" -> printHelp();
            case "nozaki" -> new IncomeAndExpenditureManagement().run(args);
            case "nakamaki" -> new Omikuji().run(args);
            case "murata" -> SubscriptionManagement.main(args);
            case "gohara" -> new Suggest().run(args);
            default -> printHelp();
          }
        } catch (AppException e) {
            System.out.println(e.getMessage());
        }
    }

    private static void printHelp() {
        System.out.println("実行アプリを指定してください。指定可能アプリは以下の通りです。");
        System.out.println("nozaki, nakamaki, murata, gohara");
    }
}
